version: '3.7'

services:
    db:
      build:
        context: prisma/.
      image: fsw/db
      container_name: fsw_db
      volumes:
      - fsw_volume_data:/var/lib/postgresql/data
      ports:
      - "5432:5432"
    app:
      build:
        context: .
      depends_on:
        - db
      image: fsw/app
      container_name: fsw_app
      volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
      ports:
      - "3001:3000"

networks:
  default:
    external:
      name: fsw

volumes:
  fsw_volume_data:
    external: true